name: ${project.name}
version: ${project.version}
description: ${project.description}
author: 2277
website: ${project.url}

main: net.socialhangover.spreadplayers.SpreadPlugin
api-version: 1.14

commands:
  spread:
    description: Administrative commands
  tpa:
    permission: spread.tpa
  tpaccept:
    permission: spread.tpaccept
  tpdeny:
    permission: spread.tpdeny
  tpignore:
    permission: spread.tpignore

permissions:
  spread.*:
    description: Grants access to all SpreadPlayer commands
    children:
      spread.reload: true
      spread.reset: true
      spread.tpa: true
      spread.tpaccept: true
      spread.tpdeny: true
      spread.tpignore.bypass: true
  spread.reload:
    default: op
  spread.reset:
    default: op
  spread.tpa:
    default: true
  spread.tpaccept:
    default: true
  spread.tpdeny:
    default: true
  spread.tpignore:
    default: true
  spread.tpignore.bypass:
    default: op