name: SpreadPlayers
version: 1
description: New player onboarding as seen on play.socialhangover.net
author: 2277
website: https://github.com/2277/spreadplayers

main: net.socialhangover.spreadplayers.Plugin
api-version: 1.14